version: 0.2

phases:
  build:
    commands:
      - dotnet restore $CODEBUILD_SRC_DIR/OrderBookWebService/src/OrderBookWebService/OrderBookWebService.csproj
      - dotnet publish -c Release -o out $CODEBUILD_SRC_DIR/OrderBookWebService/src/OrderBookWebService/OrderBookWebService.csproj
artifacts:
  files:
    - OrderBookWebService/src/OrderBookWebService/out/*
