version: 0.2

phases:
  build:
    commands:
      - dotnet restore $CODEBUILD_SRC_DIR/OrderBookWebService/src/OrderBookWebService/OrderBookWebService.csproj
      - dotnet build $CODEBUILD_SRC_DIR/OrderBookWebService/src/OrderBookWebService/OrderBookWebService.csproj
artifacts:
  files:
    - bin/Debug/bobapp/*
